name: Develop

env:
  IMAGE_TAG: asia-southeast1-docker.pkg.dev/image-ascii/image-ascii/develop:${{github.sha}}
  GCP_REGION: asia-southeast1

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build first stage
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: image-ascii-build
          outputs: type=docker,dest=/tmp/image-ascii-build.tar
          cache-from: type=gha
          cache-to: type=gha
          target: build
      
      - name: Build second stage
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{env.IMAGE_TAG}}
          outputs: type=docker,dest=/tmp/image-ascii.tar
          cache-from: type=gha
          cache-to: type=gha

      - name: Upload base image artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-ascii
          path: /tmp/image-ascii.tar

  deploy:
    needs: build
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GCP Authentication (CI/CD)
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CI_CD_SERVICE_ACCOUNT_DEV }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image-ascii
          path: /tmp

      # Load base image
      - run: docker load --input /tmp/image-ascii.tar

      # Configure docker
      - run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      # Push final image
      - run: docker push ${{env.IMAGE_TAG}}

      # Deploy to cloud run
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'image-ascii-develop'
          image: ${{env.IMAGE_TAG}}
          region: ${{env.GCP_REGION}}
